<template>
  <div>
    <div class="card mx-3 shadow-sm rounted position-relative">
      <div class="card-body p-3">
        <div class="header">
          <div class="featuresButton d-inline float-right">
            <ul class="cButtonGrid float-left">
              <li v-if="cardData.lock">
                <button class="cButton">
                  <i class="fas fa-lock"></i>
                </button>
              </li>
              <li>
                <button class="cButton">
                  <i class="fas fa-edit"></i>
                </button>
              </li>
              <li>
                <button class="cButton">
                  <i class="fas fa-trash"></i>
                </button>
              </li>
            </ul>
          </div>
          <h4 class="googleFont-m text-muted text-capitalize d-inline">
            {{ cardData.header }}
          </h4>
        </div>

        <hr />
        <p class="mb-0 pb-1 text-justify googleFont text-muted">
          {{ cardData.content }}
        </p>
        <div class="progress timeBar mt-2">
          <div
            class="progress-bar"
            :style="{ width: timebar + '%', background: colorbar }"
            role="progressbar"
            aria-valuenow="25"
            aria-valuemin="0"
            aria-valuemax="100"
          ></div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import { time } from "./time.js";
export default {
  // eslint-disable-next-line no-undef
  props: ["cardData"],
  mixins: [time],

  data() {
    return {
      timebar: this.cardData.finishTime - this.cardData.startTime,
      colorbar: "#007944",
      timeHalf: null
    };
  },
  methods: {
    countDownTimer(first) {
      var th = this;
      setInterval(function() {
        if (th.timebar > 0) {
          th.timebar--;
          if (th.timebar == first * 0.3) {
            th.colorbar = "#e25822";
          } else if (th.timebar == first * 0.1) {
            th.colorbar = "#9d0b0b";
          }
        }
      }, 100);
    }
  },
  created() {
    this.countDownTimer(this.timebar);
  }
};
</script>

<style lang="scss" scoped>
.featuresButton {
  position: absolute;
  top: 5px;
  right: 5px;
}

h4:before {
  font-family: "Font Awesome 5 Free";
  font-weight: 900;
  content: "\f12a";
  color: #b22222;
  margin-right: 3px;
}

.timeBar {
  width: 70%;
  height: 8px !important;
}

.cButtonGrid {
  list-style-type: none;
  li {
    float: left;
    margin: 3px 5px;
  }
}
.cButton {
  all: initial;
  border-radius: 50%;
  border: none;
  background: none;
  color: #393e46;
  cursor: pointer;
  &:hover {
    .fa-lock {
      color: #ec9b3b;
    }
    .fa-edit {
      color: #0c9463;
    }
    .fa-trash {
      color: #9d0b0b;
    }
  }
}
.card {
  cursor: pointer;
}

.card:hover {
  -webkit-animation: shadow-drop-br 0.4s cubic-bezier(0.25, 0.46, 0.45, 0.94)
    both;
  animation: shadow-drop-br 0.4s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2019-12-8 21:33:54
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

@-webkit-keyframes shadow-drop-br {
  0% {
    -webkit-box-shadow: 0 0 0 0 transparent;
    box-shadow: 0 0 0 0 transparent;
  }
  100% {
    -webkit-box-shadow: 12px 12px 20px -12px rgba(0, 0, 0, 0.35);
    box-shadow: 12px 12px 20px -12px rgba(0, 0, 0, 0.35);
  }
}
@keyframes shadow-drop-br {
  0% {
    -webkit-box-shadow: 0 0 0 0 transparent;
    box-shadow: 0 0 0 0 transparent;
  }
  100% {
    -webkit-box-shadow: 12px 12px 20px -12px rgba(0, 0, 0, 0.35);
    box-shadow: 12px 12px 20px -12px rgba(0, 0, 0, 0.35);
  }
}
</style>
